export const ROUTES = {
  api: '/api',
  ping: '/ping',
  users: {
    base: '/users',
    register: '/register',
    login: '/login',
    profile: '/profile',
    progress: '/me/progress',
    badges: '/me/badges',
    tips: '/me/tips',
    leaderboard: '/leaderboard',
  },
  auth: {
    base: '/auth',
    refresh: '/refresh',
    logout: '/logout',
  },
  tips: {
    base: '/tips',
    list: '/',
    create: '/',
    detail: '/:id',
    update: '/:id',
    delete: '/:id',
  },
  moderation: {
    base: '/moderation',
    reports: '/reports',
    reportResolve: '/reports/:id/resolve',
    tipsPending: '/tips/pending',
    tipsApprove: '/tips/:id/approve',
    tipsReject: '/tips/:id/reject',
    stats: '/stats',
    history: '/history',
    promote: '/users/promote',
    demote: '/users/demote',
  },
  grades: {
    base: '/grades',
    list: '/',
    detail: '/:id',
  },
};
